"""empty message

Revision ID: b7dcc754f627
Revises: 761855256d2a
Create Date: 2021-10-28 18:51:26.507615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dcc754f627'
down_revision = '761855256d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # adds a new column to the table with nullable values to allow for
    # old data to be added
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    # sets all null values to false as that is the default
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    # updates completed column to not allow null values (which is what
    # we originally wanted)
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
