"""empty message

Revision ID: db5b8d92bd37
Revises: dd6b50852b66
Create Date: 2021-11-01 17:27:06.569878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5b8d92bd37'
down_revision = 'dd6b50852b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute('UPDATE todolists SET completed = False WHERE completed IS NULL;')

    op.alter_column('todolists', 'completed', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
